### ISSUE TITLE
two issues in pack.swift

### ISSUE THREAD

**Issue by jasonhe88** [michael-yuji/MessagePack#2]
in Xcode 7.2(7C68), there are two issues in pack.swift.

/Users/jasonhe/MessagePack/src/pack.swift:96:16: No calls to throwing functions occur within 'try' expression

/Users/jasonhe/MessagePack/src/pack.swift:350:32: No calls to throwing functions occur within 'try' expression

**Comment by michael-yuji** [comment]
Hi jason, those "issues" were because of some legacy code of pack.swift that i forget to remove try! in new version, which should not affect the performance. Will fix it in next update

**Comment by michael-yuji** [comment]
Fixed
