### ISSUE TITLE
carthage and cocoapods

### ISSUE THREAD

**Issue by alec-c4** [michael-yuji/MessagePack#3]
Could you please add support for carthage and cocoa pods?

**Comment by michael-yuji** [comment]
Hi!! 
I'll love to add carthage and cocoa pods support but since I'm really busy recently and I never make a cocoa pod before I think I will add them within 2-3 months.

**Comment by prcela** [comment]
Hello
Can you write an example in readme file for case when there is some custom struct inside the other custom struct. It will be helpful because data in most cases have such hierarchy.

BTW, I preferred your swift message packer because you have the most informative and helpful readme file.

**Comment by michael-yuji** [comment]
@prcela Hi! I'm glad you like my message packer. 
To pack a custom struct inside other other custom struct you can follow the following example. I will add more documentations and examples and I'll make a wiki page for the message packer soon ^ ^.

``` swift
struct MyRootStruct: Packable
{
    var intVal: Int
    var doubleVal: Int
    var strVal: String

    func packFormat() -> [AnyObject] {
        return [intVal, doubleVal, strVal]
    }
}

struct MyOtherLevelStruct: Packable {
    var root: MyRootStruct
    var otherStrVal: String

    func packFormat() -> [AnyObject] {
        return [Mask(root), otherStrVal]
    }
}
```

**Comment by prcela** [comment]
Great!

**Comment by prcela** [comment]
How to pack optional variable? Like Int? or String?

**Comment by prcela** [comment]
How to pack such structure that contains array of root structure?

```
struct MyOtherLevelStruct: Packable {
    var roots: [MyRootStruct]
    var otherStrVal: String

    func packFormat() -> [AnyObject] {
        return [ ? , otherStrVal]     // <-- Value of type [MyRootStruct] doesn't conform to expected element type AnyObject.
    }
}
```

**Comment by prcela** [comment]
Ah, I found the reason for error. **AnyObject** must be a class, it cant be a **struct**. So, MyOtherLevelStruct must be actually a class.

**Comment by michael-yuji** [comment]
Hi @prcela , sorry for late reply. Actually, if you look closer to the example, you would find `Mask(MyRootStruct)` is used for wrapping types (bool, uint, etc..) that are not confirm to `AnyObject`.

**Comment by michael-yuji** [comment]
The Mask class will mask packable struct, bool, and uint into a packable class and pack the item. For nil, I forgot to implement the public pack method for it, I'll fix it in the next push.

**Comment by prcela** [comment]
Huh. I tried to use Mask(roots) but it wont help. 
I am on latest public XCode 7.3 with latest swift.

The build error is on same line:
"Can not invoke initializer for type Mask with an argument list of type ([MyOtherLevelStruct])"

Mask can be initiated with packable struct, but not with array of packable structs.

I would suggest to make function packFormat() -> [AnyObject**?**] with optional any object, because inside function pack_any_type you are already using item which is optional (T?).

Even if I change MyRootStruct to class I don't know how to unpack it properly.

**Comment by prcela** [comment]
Here is my complete playground, so if you can help about unpacking some data :)

```
//: Playground - noun: a place where people can play

import UIKit

var str = "Hello, playground"

class Tecaj: Packable
{
    var id: Int = 0
    var iznos: Double = 0
    var naziv: String = ""
    var poredak: Int = 0


    func packFormat() -> [AnyObject] {
        return [id,iznos,naziv,poredak]
    }
}

struct Ponuda: Packable
{
    var ident: Int = 0
    var razradaId: Int = 0
    var tecajevi = [Tecaj]()

    func packFormat() -> [AnyObject] {
        return [ident, razradaId, tecajevi]
    }
}

var p = Ponuda()
p.ident = 1; p.razradaId = 2;

var t0 = Tecaj()
t0.id = 0

var t1 = Tecaj()
t1.id = 1

p.tecajevi = [t0,t1]

let packed = packItems([Mask(p)])

do {
    let unpacked = try packed.unpack()
    print(unpacked[0].castToInt)

    // how to get t0 and t1 ?
}


```

**Comment by michael-yuji** [comment]
So far there's no good way to pack an array of custom objects directly and since it's not a generic message pack feature I've to find some ways to implement this feature without breaking compatibility with other message pack libraries (None of the other libraries support this feature).

The custom struct packing feature is basically pack every items you specifics at Packable protocol as the sequence you specified. However when I design this feature I didn't think about complex data structures. (And It will probably be the main feature of next update).

To unpack a custom packed object, us the unpackByGroupsWith... function to reassemble your struct

``` swift

let packed = packItems([Mask(p)])

do {

    var reassemed_ponudas = [Ponuda]()

    try packed.unpackByGroupsWith(3 /* number of item you have in packFormat() */,
                       numberOfSetsToUnpack: 1 ,
                       handlerForEachGroup: { (unpackedData, isLast) -> Bool in

        var reassembled_ponuda = Ponuda(ident: unpackedData[0].castToInt, razradaId: unpackedData[1].castToInt, tecajevi: [])

        reassemed_ponudas.append(reassembled_ponuda)

        // You can check condition to decide if you want to proceed unpacking by 
        // return true(proceed)/false(break)
        return true
    })   
}
```

**Comment by michael-yuji** [comment]
The reason why I didn't make packAnyItems to take AnyObject? Is because sometimes the function reads nil instead of actually value in runtime. Same thing for bool, the swift runtime somehow will read true as int 1, false as 0 when I use control flow to check the dynamic type. Therefore custom struct, bool, uint and Int32 family require the mask class.

**Comment by prcela** [comment]
Thank you for fast and detailed response.
I tried to use this message pack for getting data from the server, unpacking it to complete hierarchical model, saving it locally to file as data, load it and unpack if necessary.
Unfortunately, if there is no way to unpack the values of t0 and t1 from array, I cant use it for such purpose :(
If this doesn't work, then what is the alternative way to un/pack array of custom packable objects?
Am I missed something?

**Comment by michael-yuji** [comment]
There're no way yet for the message packer to do it directly, however, you can still engineer around it. Below is a working example, assuming you only have one `ponuda` struct and a lot of `Tecaj`

``` swift
class Tecaj: Packable
{
    var id: Int = 0
    var iznos: Double = 0
    var naziv: String = ""
    var poredak: Int = 0


    func packFormat() -> [AnyObject] {
        return [id,iznos,naziv,poredak]
    }
}

struct Ponuda: Packable
{
    var ident: Int = 0
    var razradaId: Int = 0
    var tecajevi = [Tecaj]()

    func packFormat() -> [AnyObject] {
        var array: [AnyObject] = [ident, razradaId]

        for item in tecajevi {
            array.appendContentsOf(item.packFormat())
        }

        // Now the the packer will pack your struct like this:
        // +-----+---------+---+---+---+---+---+---+---+---+
        // |ident|razradaID|first tecaj | second |.......
        // +-----+---------+---+---+---+---+---+---+---+---+
        return array
    }
}

var p = Ponuda()
p.ident = 1; p.razradaId = 2;

var t0 = Tecaj()
t0.id = 0

var t1 = Tecaj()
t1.id = 1

p.tecajevi = [t0,t1]



let packed = packItems([Mask(p)])

do {

    // first unpack the ponuda struct header, and get the remaining bytes
    let unpacked = try packed.unpack(specific_amount: 2, returnRemainingBytes: true)

    var ponuda = Ponuda(ident: unpacked[0].castToInt, razradaId: unpacked[1].castToInt, tecajevi: [])

    // now the unpack the remaining bytes by groups, and reassem your structs in array
    try unpacked[2].unpackByGroupsWith(4, handlerForEachGroup: { (unpackedData, isLast) -> Bool in

        var new = Tecaj()

        new.id = unpackedData[0].castToInt
        new.iznos = unpackedData[1].castToDouble
        new.naziv = unpackedData[2].castToString()!
        ponuda.tecajevi.append(new)
        return true
    })

    print(ponuda.tecajevi[0].id)
    print(ponuda.tecajevi[1].id)

}
```

**Comment by michael-yuji** [comment]
@prcela  Here is another example, which works for multiple Ponuda

``` swift
class Tecaj: Packable
{
    var id: Int = 0
    var iznos: Double = 0
    var naziv: String = ""
    var poredak: Int = 0


    func packFormat() -> [AnyObject] {
        return [id,iznos,naziv,poredak]
    }
}

struct Ponuda: Packable
{
    var ident: Int = 0
    var razradaId: Int = 0
    var tecajevi = [Tecaj]()

    func packFormat() -> [AnyObject] {
        var array: [AnyObject] = [ident, razradaId]

        array.append(tecajevi.count)

        for item in tecajevi {
            array.appendContentsOf(item.packFormat())
        }

        // Now the the packer will pack your struct like this:
        // +-----+---------+-----------+---+---+---+---+-----+
        // |ident|razradaID| arrayCount|first tecaj | second |.......
        // +-----+---------+-----------+---+---+---+---+---+-+
        return array
    }
}

var p = Ponuda()
p.ident = 1; p.razradaId = 2;

var t0 = Tecaj()
t0.id = 0

var t1 = Tecaj()
t1.id = 1

p.tecajevi = [t0,t1]

var p2 = Ponuda()
p2.ident = 2;
p2.razradaId = 3

p2.tecajevi = [t0, t1]


let packed = packItems([Mask(p), Mask(p2)])

do {
    var holder = [Ponuda]()
    var unpacked = try packed.unpack()

    var i = 0 // count how many objects handlered in totoal
    while unpacked.count > i {
        var j = 0 // count how many objects this section handlered

        var newPonuda = Ponuda(ident: unpacked[i + 0].castToInt,
                               razradaId: unpacked[i + 1].castToInt,
                               tecajevi: [])

        j += 3 // one for ident, one for razradaId, one for arrayCount
        for numItem in 0..<(unpacked[i + 2].castToInt) {
            let new = Tecaj()
            let baseIndex = i + 3 + numItem * 4
            new.id = unpacked[baseIndex].castToInt
            new.iznos = unpacked[baseIndex + 1].castToDouble
            new.naziv = unpacked[baseIndex + 2].castToString()!
            new.poredak = unpacked[baseIndex + 3].castToInt
            newPonuda.tecajevi.append(new)
            j += 4 // 4 items handled
        }
        i += j

        holder.append(newPonuda)
    }
    print(holder[0].tecajevi[0].id)
    print(holder[0].tecajevi[1].id)
    print(holder[1].tecajevi[0].id)
    print(holder[1].tecajevi[1].id)
}
```

**Comment by prcela** [comment]
Thanks man for your time and complete sample code.
👍 

I found some message packer sample that works with json which is structurally similar. Note, that it contains some phoneNumbers field that is array of some structs. I mean in general that message packer concept should deal with array of custom objects.

https://github.com/jakm/msgpack-cli

**Comment by michael-yuji** [comment]
All JSON should be able to convert to message pack map since it's all key value binding.
However to implement an actual C-like struct to message pack instead of using map to emulate (like how JSON work) should be able to save a lot of overhead (no need for unnecessary keys).

I wish one day they will come up with a standard for custom struct too.

**Comment by michael-yuji** [comment]
@alec-c4 Cocoapods support is added

**Comment by alec-c4** [comment]
thanks a lot!!! 👍
