### ISSUE TITLE
Fails for floats or doubles

### ISSUE THREAD

**Issue by BrettThePark** [michael-yuji/MessagePack#4]
I can't seem to get anything to pack properly for floats for doubles.

```
  func testPack() {
    let dt = 1.0
    let pack = dt.pack()
    do {
      let unpacked = try pack.unpack()
      XCTAssertEqual(unpacked[0].castToDouble, dt)
    } catch {
      XCTFail("\(error)")
    }
  }
```

Fails with 

```
float64
false
UnknownDataType_cannot_find_type_to_match_prefix
```

I also have tried with an array full of doubles or floats.

**Comment by BrettThePark** [comment]
After review, the code was missing a couple types for Float32 and Float64. When unpacking, the bytes are properly flipped back. Also, arrays with floats will still fail after that.

**Comment by michael-yuji** [comment]
you're right, I've totally forgot that the floats in message packed format is in network byte order. It's fixed now. (when pack individually)

For the arrays and "packItems" function, for some reason the swift runtime failed to recognize double as double when using `case is Double`, same thing happens on Bool and Int as well. I'm going to rewrite those parts and fix it in the next update.

**Comment by michael-yuji** [comment]
Alright, everything is fixed now.
